### ISSUE TITLE
pozdni commit aka bordel

### ISSUE THREAD

**Issue by mtravnicek** [javorka/PA165#12]
ahoj omlouvam se za zmatek, ale dal jsem tam jeste jeden commit a jak koukam tak mi to tam zas pridalo nejaky podivny dalsi ID, to mam asi nekde v pocitaci nevim... plus to co jsem tam komitnul, je to vhodne na to upozornovat, kdyz to tam jeste nekde chybi.... umi to nekdo a chce pripadne smaznout? http://stackoverflow.com/questions/448919/how-can-i-remove-a-commit-on-github

**Comment by m-krajcovic** [comment]
no dostal som mini infarkt rano, nabuduce radsej uz nic necommituj pred deadlinom ked to funguje :D inac v commite tvojom nevidim nic okrem zmeny javadocu
