### ISSUE TITLE
domluva na milestone 2 

### ISSUE THREAD

**Issue by mtravnicek** [javorka/PA165#13]
zdravim, nemate nekdo cas se potkat na pocitacich a probrat ten novy milestone?
klidne jeste dneska nebo pristi tyden...
nebo aspon neco napiste, co ty 2 business functions on service layer...
chtelo by to nejak rozdelit kdo co bude delat, sef tymu? :)
jinak bych zkusil pouzit thymeleeaf misto jsp, pokud se to smi (a budete souhlasit)
plus jsem nasel jakousi kompletni testovaci vyvojovou platformu pro spring zalozenou na eclipsu
kde je mnostvi Getting Started hotovych projektu, instalovanych "jednim kliknutim"
Spring Tool Suite (STS), muze se hodit....
https://spring.io/guides/gs/sts/

**Comment by javorka** [comment]
Thymeleafu by som sa vyhol... frontend by som chcel radsej riesit prostrednictvom angularu. Co sa tyka milestonu 2 tak ja sa zajtra na to pozrem a spravim, tak ako minule, nejaky "boilerplate" kde bude dozer, alebo daco podobne a jedna ukazkova entita

**Comment by mtravnicek** [comment]
ok sorry, ten frontend se ted vlastne nema vubec delat...

**Comment by javorka** [comment]
@mtravnicek @m-krajcovic @spisiakm navrhujem aby sme sa zajtra stretli (idealne pred cvikom) a rozdelili si pracu na druhom milestone, lebo cas sa nebezpecne krati. Kedy vam to vyhovuje?

**Comment by spisiakm** [comment]
staci o 15:00 ?

2016-11-22 21:43 GMT+01:00 javorka <notifications@github.com>:

**Comment by javorka** [comment]
za mna je to ok

S pozdravom
Peter Javorka

2016-11-22 22:52 GMT+01:00 Martin Spisiak <notifications@github.com>:

**Comment by m-krajcovic** [comment]
15 moze byt

**Comment by mtravnicek** [comment]
nahral ty svoje Order DTO+atd
jinak sorry ze jsem nedosel v ty 3 jsem si to precet na posledni chvili...

to michal :+1: mel jsem tam zas nejaky commit junk a pouzil jsem
git push -f origin HEAD^:master pro vraceni, coz funguje celkem ok, jen jsem se to ohneda bal pouzit,
tak pardon za infarkt pri tom minulem deadlinu, pocital jsem ze to na to pouzijes ty...
ps jen by to asi udelalo problem pokud nekdo mezitim neco odevzda coz? :-1:
