### ISSUE TITLE
Implement Facade layer interfaces and implementations

### ISSUE THREAD

**Issue by javorka** [javorka/PA165#16]
Everything that should happen in the system must be available through these interfaces (create entities, deleting them etc);
You must have at least 2 non-trivial business functions on Service Layer (the example project contains several of them). Service layer is not always just a place to delegate to DAO;

**Comment by spisiakm** [comment]
@javorka potom pls mergni tvoju branch s masterom (ked doplnis, co potrebujes). Spravil som commit do tvojej branche.

**Comment by mtravnicek** [comment]
ty business functions teda jake?, ja bych k Order dodelal na DAO vrstve vyhledani objednavek podle data... coz me privadi k dotazu, ze porad nevim, co vlastne ten nas projekt dela, ma delat, vy jo? co jsem se pak bavil s cvicicim, tak muzem byt i e-shop s pneumatikama...hmm, neni to tak lepsi?

**Comment by spisiakm** [comment]
Ak teda je moja business funkcia v pohode, tak treba este jednu. @m-krajcovic ty si tusim robil/chcel robit tu jednu funkciu nie ? 😄

**Comment by m-krajcovic** [comment]
jo uz soonish spravim pull request

**Comment by mtravnicek** [comment]
hej tak co v tom Oder, dival se na toto nekdo...
https://github.com/fi-muni/PA165/blob/master/eshop-service/src/main/java/cz/fi/muni/pa165/service/OrderServiceImpl.java

**Comment by spisiakm** [comment]
btw spravime aj javadoc ?

**Comment by javorka** [comment]
Javadoc by to asi chcelo... kazdopadne tato issue je uz hotova, zatvaram
