### ISSUE TITLE
Service tests

### ISSUE THREAD

**Issue by javorka** [javorka/PA165#18]
There must be extensive unit tests for the service layer (particularly for your 2 business functions) and all the tests of service layer must use Mock DAO objects;

**Comment by mtravnicek** [comment]
prosimte, ty si tam zacal delat AdditionalService test, pritom AdditionalServiceDaoTest sem delal ja...
muzu to dodelat, nebo jaky ty testy mam delat ja (aby v tom nebyl zmatek)

**Comment by m-krajcovic** [comment]
ten additional service test je tam len ako priklad v ktorom prakticky nic nie je, takze ano dorobit to mas ty

**Comment by spisiakm** [comment]
iba pre info, kto robi test na co ?

**Comment by javorka** [comment]
Testy (aj entity) robime rovnake ako pri prvom milestone

2016-11-24 10:37 GMT+01:00 Martin Spisiak <notifications@github.com>:

**Comment by mtravnicek** [comment]
no co je ted teda potreba jeste dodelat, resp co mam udelat ja? ten AdditionalServiceDaoTest a jeste na te druhe strane test...?

**Comment by spisiakm** [comment]
@mtravnicek no treba spravit jednoduche testy na Facade vrstvu + zlozitejsie (vyskusat vsetky mozne sposoby) testy na Service vrstvu. Test robis na to, na co minule :) tzn. ak si minule robil test na AdditionalServiceDao, tak teraz robis testy na AdditionalServiceFacade + AdditionalServiceService

**Comment by spisiakm** [comment]
Priklad, ako robit tie testy, uz mas v AdditionalServiceServiceTest, takze staci ho editnut (podla mna by si mal aj zmenit hlavicku, aby sa ten subor ratal tebe, ale je to asi viac menej jedno)

**Comment by mtravnicek** [comment]
jasne, takze ty testy, dam to asi az behem zitrka, mam ted nejakou praci...

**Comment by mtravnicek** [comment]
nebudete zitra nekdo na pocitacich?

**Comment by spisiakm** [comment]
Neviem, ja pravdepodobne nebudem mat cas ist do skoly aj.

**Comment by javorka** [comment]
takze @mtravnicek ty dorobis zajtra tie testy? Do kedy? Lebo ak sa objavi nieco necakane, nech to mame cas opravit. Ja dnes napisem vsetky moje testy. Ako ste na tom vy @m-krajcovic a @spisiakm ?

**Comment by mtravnicek** [comment]
v nejake rozumne dobe, neco snad stihnu jeste dneska, hele co ty transitions mam to tam dat
https://github.com/fi-muni/PA165/blob/master/eshop-service/src/main/java/cz/fi/muni/pa165/service/OrderServiceImpl.java
to me pride jako celkem naprd, ale je haze to tu exception, tak aspon tu zmenu stavu implementovat ni? -)

**Comment by spisiakm** [comment]
Ak nestihnem spravit tie testy dnes, tak zajtra doobeda by mali byt hotove.

**Comment by mtravnicek** [comment]
ale to findByTireType to mas nejeak blbe, hlasi error aspon an master branch to vis?

**Comment by m-krajcovic** [comment]
ja na tom robim, robil som este tu biznis funkciu a tak ale dneska by som testy mal mat

**Comment by mtravnicek** [comment]
aha tak beru zpet nejky build bug -)

**Comment by mtravnicek** [comment]
jo mimochodem nechteli jste zredukovat ty logy, dal jsem tam ten log config na info, nevim teda k cemu tam je ten prazdny soubor hibernate? -),  k tem testum, uplne

**Comment by mtravnicek** [comment]
delam ten AdditionalServiceServiceTest
https://gist.github.com/mtravnicek/f7ac5e1c8b62382a9fd56bb27951f2a7
hele proc se toto bije skrz to serviceID a je poterba dat/nedat to setId, i kdyz dam ruzne id
nechtelo by to zas ten dirtycontext?

**Comment by m-krajcovic** [comment]
no pisem tie testy a prisiel som na taku neprijemnost - myslim, ze to maju zle v priklade ale ked pouzivam @InjectMocks s @Autowire tak to nefunguje spravne - pouziju sa normalne implementacie (volalo to hibernate a tak) a nie tie mocky, takze som odstranil z testov cely spring a uz to ide s mockami spravne - neviem teda ci ste sa stym niekto iny stretli. Takto dako teda vyzera zaciatok mojich testov a vsetko ide: 
```
public class TireServiceTest {
    @Mock
    private TireRepository tireRepository;

    @InjectMocks
    private TireServiceImpl tireService;

    private Tire tire;

    @BeforeClass
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }
```
inac @mtravnicek  musis mockovat repository, zachvilu to hadam budem mat tak to pushnem a mozes sa z toho odrazit

**Comment by mtravnicek** [comment]
aha no me to tam tez vypisuje ten hibernate...ten mock by mel bezet tak nejak virtualne ze

**Comment by javorka** [comment]
btw: mozno ste sa stretli ze vam vyhodil dozer nejaku vynimku. Vyriesil som to pridanim konfiguracie do mapovania. Okrem toho sa opravil packaging (facade impl na service vrstve) @mtravnicek tebe su opravil OrderDTO.class aby neobsahoval ziadne elementy z perzistentnej vrstvy

**Comment by mtravnicek** [comment]
aha, no zajimave veci to dela = stavim an tom vychozim AdditionalServiceServiceTest
```
@Test
public void save() {
        AdditionalService service = new AdditionalService();
        //service.setId(1l);
        service.setName("SomeService");
        service.setDescription("SPECIAL SERVICE");
        service.setPrice(BigDecimal.TEN);
       serviceService.save(service);
    }
```
2016-11-24 20:18:15,372 INFO  [main] impl.AdditionalServiceServiceImpl - Requested to save AdditionalService : AdditionalService{id='**null**'name='SomeService', description='SPECIAL SERVICE', price=10}

**Comment by mtravnicek** [comment]
nebo to je dobre ze to je null? a znamena to ze mock funguje...
jinak kdyz to pustis pres @RunWith(SpringJUnit4ClassRunner.class)  tak to dela to stejne ale nevypisuje to temer nic

**Comment by javorka** [comment]
@m-krajcovic tiez mi to mockovanie nefunguje. Pozrel som [toto](https://solutiondesign.com/blog/-/blogs/spring-and-mockito-happy-together) ale nefrci mi to

**Comment by m-krajcovic** [comment]
@javorka  pozri sem https://github.com/javorka/PA165/pull/25

**Comment by mtravnicek** [comment]
ok no ale tam mas mit InjectMocks TireService ne TireServiceImpl -)

**Comment by mtravnicek** [comment]
no nevim mam toho pro dnesek plne kecky, asi uz to necham na zitra....aha tak se snad zadarilo
https://gist.github.com/mtravnicek/31b815c7b4a736b08e20a812f369b354
takto by mel vypadat ten mock a funguje to
je to teda spravne ze ta entita ma id null, protoze se priradi az po ulozeni ze

**Comment by mtravnicek** [comment]
jo co si pamatuju jediny z prednasky ze @transactional ma byt az na te facade vrstve 
tady mame @service a @transactional na NecoServiceImpl a oni tam maji 
v ServiceConfiguration tohle coz odpovida souboru TestConfiguration pro srovnani:

@Configuration
@Import(PersistenceSampleApplicationContext.class)
@ComponentScan(basePackageClasses={**OrderServiceImpl.class, CategoryFacadeImpl.class}**)

ve te facadeImple je pak ta @transactional a service anotace

**Comment by spisiakm** [comment]
Order service testy su hotove

**Comment by javorka** [comment]
Finaly done
