### ISSUE TITLE
REST vrstva

### ISSUE THREAD

**Issue by spisiakm** [javorka/PA165#33]
Chalani, ten rest som uz opravil, dokumentacia bude fungovat. Jedine, co potrebujem teraz, je vediet, aky bol ten fix, ked vam nesli tie jspcka 😄 @m-krajcovic @javorka ?

**Comment by m-krajcovic** [comment]
@javorka mergni ten branch spring mvc :D V ňom to uz funguje.  ja som na mobile

**Comment by javorka** [comment]
mergujem (btw: ja uz spravil aj swaggera) :D

**Comment by spisiakm** [comment]
takze mam to brat, ze ten jsondoc uz entreba ? :D

**Comment by spisiakm** [comment]
Takže netreba @javorka ? :D

**Comment by javorka** [comment]
@spisiakm teraz som prisiel z roboty, prave pozeram v akom stave je projekt. Myslim si ze REST vrtstva je **DONE** (bud zamergujem tvoju, alebo moju verziu)

**Comment by spisiakm** [comment]
Ok, len moja verzia nemá ten jsp fix

**Comment by spisiakm** [comment]
@javorka ten swagger sa mi pozdava viac, updatol som tvoju branch so swaggerom - pridal som tam este jeden controller - tire, kde su implementovane vsetky metody. Kludne mozme dat potom merge tvojej branch. Len par poznamok: 

- Mozno by som hodil nastavil/presmeroval homepage (tzn. localhost:xxxx/eshop) na to swagger-ui.html
- Asi by bolo dobre este pridat vytvaranie aspon jedneho objektu vzdy pri nastarovani tomcatu

Mozem sa na to este mrknut, ale az niekedy neskor poobede, dnes mam toho cez hlavu (este aj skurvena diplomka) a chcem dokoncit tire mvc

**Comment by javorka** [comment]
Presmerovanie mozem spravit ak budem stihat, kazdopadne by som to riesil, az ked to bude hotove. Co sa tyka vytvarania objektov, tak je vytvoreny modul sample-data, ktory toto riesi(uz je zamergovany v mastri)

**Comment by m-krajcovic** [comment]
nepozeral som ten rest len pripominam :D 

> The REST must be accessible at http://localhost:8080/pa165/rest

**Comment by spisiakm** [comment]
aha diky za pripomenutie :D momentalne je na http://localhost:8080/eshop 😆

**Comment by javorka** [comment]
done
