### ISSUE TITLE
MVC layer

### ISSUE THREAD

**Issue by javorka** [javorka/PA165#38]
Ahoj,
v akom stave je MVC layer? Moc mi to nefuguje (up-to-date master). Pracujes na tom? Ak ano, do coho sa mam pustit, nech nerobime to iste dvaja?
@m-krajcovic

**Comment by m-krajcovic** [comment]
Cauko, idem pushnut novu verziu kde funguje uz normalne aj home (localhost:8080/pa165/) a tam uz setko fici ako ma :D 

daj mi par minut, inac mozes skussit napr localhost:8080/pa165/user/ to by malo fungovat v mastri o_O

**Comment by javorka** [comment]
Super! Dobra praca :)

**Comment by m-krajcovic** [comment]
tak je to tu https://github.com/javorka/PA165/pull/39 , mergnem to hned len nech dobehne travis aspon :D pak uz funguje ten home atd , ak sa ti bude chciet sa pohrat s tym footer.css (vymazal som ti to sorry, dako to bolo dojebane) tak uz je pridany v template.tag takze je to na kazdej stranke ked tak (bolo treba len zaregistrovat resources v mvc configu)

**Comment by javorka** [comment]
Vsetko funguje. Zatvaram
