### ISSUE TITLE
Create 4 entities + DAO interface

### ISSUE THREAD

**Issue by spisiakm** [javorka/PA165#4]
Create entities
- Person (a general class, could be further differentiated as a Customer and as a Mechanic)
- Order
- Tire
- Inspection
- relevant DAO interfaces & CRUD operations using JPA

**Comment by spisiakm** [comment]
Inspection - @javorka 
Tire - @spisiakm 
Order - @mtravnicek 
Customer - @m-krajcovic

**Comment by spisiakm** [comment]
Other entities, which could be implemented later:
- Invoice
- Vehicle
- Service
- Inspection Type

**Comment by m-krajcovic** [comment]
toto sme dosiahli na cviku:
<img width="506" alt="screenshot 2016-10-26 18 53 29" src="https://cloud.githubusercontent.com/assets/6861709/19735886/a86c2850-9bad-11e6-85bf-177fe5d195be.png">
ja si myslim, ze to je moc komplikovane a mohli by sme to jednoducho dat na nieco taketo (je to skoro to iste ako sme mali na zaciatku ale trosku ine):
<img width="412" alt="screenshot 2016-10-26 19 17 33" src="https://cloud.githubusercontent.com/assets/6861709/19736759/f0b8791c-9bb0-11e6-9d7a-4316f4affa6d.png">
takto by to bolo jednoduche: zakaznik ma 0..* objednavok, jedna objednavka ma vzdy len 1 pneumatiky a drzi si ich pocet, pri pneumatikach drzime pocet kolko ich je na sklade.
Tych dodatocnych sluzieb moze mat objednavka 0 az viac, ale vzdy to bude len jedna sluzba (neobjedna si napr 4x cistenie kolies, ale len raz)

**Comment by javorka** [comment]
suhlasim... ale navrhujem pridat **OrderItem**, ktore by obsahovalo atributy **count** a **price**, aby sme sa vyhli problemu ked si niekto objedna viackrat jednu vec ( 4x jednu pneumatiku)

**Comment by m-krajcovic** [comment]
ved ten count a price uz je v Order, nechapem presne potom co myslis tym OrderItem, ak by to malo byt v 1:1 s Order tak to nedava zmysel

**Comment by javorka** [comment]
Order by obsahovala List<OrderItem>, bez zavislosti na Tire a AdditionalService
OrderItem by obsahoval **bud** Tire **alebo** AdditionalService. Dalejpocet objednani a vyslednu cenu. Order by vobec nemuselo mat cenu. Aleboby by nebola ukladana ale iba pocitana (@Transient). Chapeme sa? Chcem docielit moznost pridavat do objednavky jednu polozku viac krat

**Comment by m-krajcovic** [comment]
No uz chapem ako to myslis, ale podla mna to zbytocne komplikujes, ved ked si objednas prezuvanie pneumatik tak staci, ze mas na jednu objednavku jedny pneumatiky. Doplnkovych sluzieb sa normalne da objednat aj viac. Myslim, ze by sme to mali spravit fakt co najprimitivnejsie a so 4 entitami, hentym len pridavas featuru, ktoru neni treba. 

S tym price v order suhlasim to netreba aby bol atribut staci to pak dopocitat.

**Comment by javorka** [comment]
V poriadku, mozme to aj tak spravit, len ak to budeme casom prerabat tak budeme musiet prerabat aj unit testy a dalsie entity koli vazbam (v tomto pripade by sa nezmenil iba Customer)
Co sa tyka toho dopocitania ceny, tak by som to robil iba v pripade, keby sme zaviedli OrderItem, ktora by obsahovala cenu. Lebo inak by mohla nastat situacia ze po update ceny v **Tire** by sa updatli aj vsetky objednavky (aj historicky stare) - cena by sa prepocitala s novymi hodnotami.

**Comment by m-krajcovic** [comment]
Nemyslim ze to bude treba prerabat, vraj budeme robit cele s tym ako zacneme. 

Teraz mi este napada, ze by bolo vhodne upravit Customer na User + pridanie enum UserRole (cviciaci vravel ze je enum lepsi ako zbytocne to komplikovat dalsou entitou) 
- User by mal teda email, meno, heslo, roles
- Telefon a adresu pridat do Order - tiez to dava zmysel aby mohla mat kazda objednavka tieto veci rozne

Toto by sme museli upravit tak ci tak pretoze tam potrebujeme aj admina

**Comment by javorka** [comment]
S tym Customer -> User plne suhlasim. Aj s tym presunutim telefonu a adresy do objednavky.

Ako hovorim, mozme to urobit bez tej OrderItem, ale nebudeme moct pridavat 2 rovnake polozky (Tire, AdditionalService) na jednu Order. To je v podstate jediny use case, koli ktoremu to chcem vytvorit.

**Comment by m-krajcovic** [comment]
No ja chapem a urcite by som suhlasil, len to v tomto projekte nema cenu tak robit.
Ono je trosku zavadzajuce to nazvat "Order", mozno by bolo vhodnejsie nieco ako "TireChange" a uz by to davalo vacsi zmysel. V zadani je, ze jedine co si zakaznik objednava je prezutie pneumatik + dodatocne sluzby k tomu a nerobi si daku velku objednavku, ktoru pak naraz zaplati.

**Comment by m-krajcovic** [comment]
V ramci zjednodusovania mi este napadlo:
- odobrat quantity z Tire aj Order a jednoducho neriesit kolko chce prezut kolies

ALEBO
- odobrat len quantity z Tire, pretoze to moze byt jedno kolko ich je na "sklade"

Viem ze mozno je to kus nelogicke, ale v tomto projekte by malo ist fakt o jednoduchost a precvicenie tych technologii a nie o to aby sme vytvorili najskvelejsi system pre pneuservis :D

**Comment by spisiakm** [comment]
K tomu Customer -> User - jasne, bavili sme sa aj o tom, ten Customer som myslel skor ako nieco vseobecnejsie (tusim som to tam aj dal ako Person potom). Ten Class diagram o styri prispevky vyssie je vcelku v pohode, ten stock u Tire nemusi byt. V Order by som quantity nechal.

**Comment by spisiakm** [comment]
Btw len taka poznamka bokom, ak budeme pridavat dalsiu funkcionalitu a kvoli tomu prerabat vcelku vela kodu, tak to by znamenalo, ze velku modularitu nemame a mame vela zavislosti (co nie je dobre)

**Comment by m-krajcovic** [comment]
Pridal som User entitu s DAO do mastru 2188a75c682b0ec60886a4ec933aaf52cebff067

**Comment by m-krajcovic** [comment]
Vsimol som si, ze pri generovani equals/hashcode v intellij v triede ktora dedi z abstraktnej sa do equals prida riadok `if (!super.equals(o)) return false;` co pokazi equals, pretoze v superclasse (AbstractEntity/AbstractAuditedEntity) je equals len povodny. Prepisal som to v Userovi (b02e30eb3ab07b5ef4508850fe7e7bf136012ac8 ) tak to popripade asi tiez ztade potom zmazte zo svojich entit.

Pridal som tiez javax.validation ako bolo na cviku :)

**Comment by spisiakm** [comment]
Ok, pushol som tam moje zmeny. Z Usera som tiez vybral ten enum Role, a dal to do samostatneho suboru (drobnost, len pre citatelnost). Najskor som sa zlakol, ze nerobime ziadne DAO interface, ale potom mi doplo, ze pouzivame tu JPA repo, kt. uz ma implementovane tie CRUD operacie 👍
