### ISSUE TITLE
Missing requierements

### ISSUE THREAD

**Issue by javorka** [javorka/PA165#43]
Podla poziadaviek na milestone 3 nam uz chybaju iba tieto veci:

- [x] Form validation
- [x] Zabezpecenie ciest 
- [x] Vsetku logiku zobrazit v MVC 

Zabudol som na nieco?

**Comment by m-krajcovic** [comment]
Zabezpečenie ciest tým myslíš co? Ja mam v controlleri dake veci co môže robiť len admin napr. Ten form validation urcite treba no lrn nevim presne jak na to.. Oni tam používajú validation anotácie ne? Ale my mame tie dto čisté :D moc som to neskusal... Popripade vyrobiť vlastne validatory formulárov no.

**Comment by spisiakm** [comment]
form validatory - nieco ako https://github.com/fi-muni/PA165/blob/master/eshop-spring-mvc/src/main/java/cz/muni/fi/pa165/mvc/forms/ProductCreateDTOValidator.java ?

**Comment by javorka** [comment]
Zabezpecenim ciest myslim PreAuthorize - to bude na par minut. Otazne je, ako spravime tu validaciu. Pravdepodobne by to slo pridanim anotacii do DTO (NotNull, Min, Max...) a potom v controlleri pomocou anotacie Valid (nemam ju nastudovanu)

**Comment by m-krajcovic** [comment]
Jo chcelo by to pozret ako to majú v školskom oni. Ja som tak za pol hodku doma tak checknem a uz sa mi vybije baterka Soon tak rip :D

**Comment by javorka** [comment]
Ja si zoberiem teda zoberiem na starost validaciu.

**Comment by spisiakm** [comment]
No ja od 21:15 cestujem domov, a uz nebudem potom dnes na nete 😄

**Comment by spisiakm** [comment]
ja doplnim este logiku ku Tire, aby tam bolo vsetko (nejaky search box pre vyhladavanie podla tire type + vygenerovat 3 najpredavanejsie)

**Comment by javorka** [comment]
@spisiakm na vyhladavanie sa vykasli... tie najpredavanejsie sprav :D

**Comment by spisiakm** [comment]
Ok, spravene najpredavanejsie (vo view sa to da filtrovat, ci chcem vsetky tires alebo iba tri najpredavanejsie). Kedze ale su v databazi iba dve pneumatiky, tak to vypise iba tie dve :D . Updatol som aj RestController, aby tam bola ta funkcionalita. Pushnute do mastra.

**Comment by javorka** [comment]
@m-krajcovic spravil som validaciu, a hlasky taham z ResouceBundle, Problem je, ze sa stale snazi najst slovensky Locale, ktory tam nemam. Stretol si sa s niecim podobnym?

**Comment by m-krajcovic** [comment]
a mas tam defaultny bundle? myslim tym ze tam mas napr len "Texts_en.properties" a chyba ti nieco ako "Texts.properties" (to je default ked sa nenajde locale)

**Comment by javorka** [comment]
mam iba "Texts.properties" a chcem aby to tahalo odtial :D

**Comment by m-krajcovic** [comment]
a skusal si tam pridat aj ten "Texts_en.properties" aspon ? :D 

inac kde mas tu validaciu? pozeram na to akurat a su tam teda dve moznosti - anotacie na dto alebo validatory

ja potrebujem ine validacie pri editovani usera a ine pri registracii takze dava asi zmysel vytvorit na to dve rozne DTO, lenze tie fasady nam beru len to jedno takze neviem teraz co s tym :D

**Comment by javorka** [comment]
ja som iba pridaval anotacie nad DTO.

**Comment by javorka** [comment]
Spravil som easy validacie, ale funguju :D upravim AdditionalService a Tire. Na Usera si netrufam (aby som to nerozbil) a na Order este nie je kde

**Comment by mtravnicek** [comment]
mrkni na ten branch

**Comment by m-krajcovic** [comment]
@javorka @spisiakm este pozrite na ten branch od @mtravnicek na https://github.com/javorka/PA165/tree/order-mvc a mergnite to ked tak, ja uz nedavam :D

**Comment by m-krajcovic** [comment]
@javorka @spisiakm inac pozeram ze travis trva riadne dlho na rest module, mrknite na to pls tiez ked tak

**Comment by spisiakm** [comment]
Jediné, čo ma napadá, prečo môže trávia bežať tak dlho nad rest modulom, je
vytváranie javadocu.

**Comment by mtravnicek** [comment]
tyjo neim jak nalit a vylit ten Additional Service do toho formulare tkay by se tam melo dat pridat jich vic jakoby tech rozeviracich oken

**Comment by spisiakm** [comment]
@mtravnicek Na to sa už asi teraz vykasli, mergneme to, čo máš. Veľa času uz nie je, a ja som na mobile, nedá sa mi veľmi zrevidovat kód. Takže ak ti to funguje ako-tak, tak daj pull request.

**Comment by javorka** [comment]
@m-krajcovic je to ten javadoc
@spisiakm pada mi TOP SELLING TIRES

**Comment by spisiakm** [comment]
Ako ti to padá ?

**Comment by javorka** [comment]
@spisiakm uz som nasiel chybu (servisna vrstva - jeden if)

**Comment by mtravnicek** [comment]
ja tam us sebe jeste chvilku neco dodelam

**Comment by javorka** [comment]
@mtravnicek davam ti cas do 23:30, potom vytvaram idem mergovat pripadne riesit konflikty a opravovat chyby. Moze byt?

**Comment by mtravnicek** [comment]
ok

**Comment by mtravnicek** [comment]
mas to v tom order-mvc

**Comment by javorka** [comment]
oka

**Comment by m-krajcovic** [comment]
ten 360 degrees tam bol ako joke, shame on you kto to prepisal na 180 :D

**Comment by m-krajcovic** [comment]
@spisiakm @javorka pocujte, ako sa dostat k tomu swaggeru ked spustim rest module? :D som to chcel vyskusat a napisat ked tak do readme ale netusim vobec ako na to

**Comment by spisiakm** [comment]
@m-krajcovic http://localhost:8080/pa165/rest/swagger-ui.html

**Comment by m-krajcovic** [comment]
super dik

**Comment by javorka** [comment]
@m-krajcovic diky ze si zamakal este aj po deadline... ja som proste odpadol o polnoci :D Treba este nieco spravit? 
PS: ja som zmenil 403 (Shame on me) :D bol som prepracovany na to aby som pochopil dajake vtipky :D
PS2: kedy budes v blizkosti skoly, aby som ti vratil mysku?

**Comment by m-krajcovic** [comment]
A tak ma to pak aj baviť začalo keď už neni deadline :D a nevim myslím že to všetko funguje docela správne teraz. Popripade dako vylepšiť UI :D 

A hej pohoda zas tak dobrý vtip to nebol :D

A hádam to neni problém ale asi až na obhajobe :D diky moc ze si ju zobral ale :)

**Comment by mtravnicek** [comment]
ahoj koukam jak jste aktivni a MichK to dodelal i za me... tak dik, i kdyz... , takovy blby dotaz, mam tam/budete jeste neco v tom projektu dodelavat? a co ta obhajoba, nevim zda tam vubec chodit, o cem to jako ma byt, tam nekdo bude oponovat ten projekt nebo co? PS ten Swagger ja tam k cemu (API?)

**Comment by spisiakm** [comment]
@mtravnicek precitaj si prosim Final Project Requirements - posledna zalozka v interaktivnej osnove seminarov z PA165 v ISe, tam su vsetky detaily tykajuce sa obhajoby projektu. Ten Swagger sluzi na dokumentaciu nasej REST vrstvy, kde si ju mozu uzivatelia taktiez vyskusat (pozri si, ako to funguje, ked si zapnes tomcat s nasou rest vrstvou, aby si vedel).

**Comment by mtravnicek** [comment]
ok..zitra bych mel mit cas se podivat na aktualni verzi... chcete/nechcete tam teda aktualne implementovat nejakou dalsi funkcionalitu/fixy? co ta prezentace? dorazite nekdo v tydnu do skoly nebo se chcete potkat az toho 11. od 14-20(?? to je jako cely den)

**Comment by spisiakm** [comment]
Ja dojdem do brna az cez vikend, takze ak budete chciet, tak sa mozme
stretnut este pred prezentaciou (ak nieco nebude niekomu jasne). Na
prezentaciu sa pozriem neskor. Fixy treba dorobit podla toho, co nam vytkli
a na co sme este prisli my. K tej obhajobe projektu - tipujem, ze nam tesne
pred obhajobou poslu casovy rozpis prezentacii, tzn. na kolku mame dojst.

2017-01-03 21:51 GMT+01:00 mtravnicek <notifications@github.com>:

**Comment by mtravnicek** [comment]
co jsem delal hodnoceni na skupinu me pridelenou, tak jim tam pri poslednim odevzdani nejelo prakticky nic - pouziti nejake funkce- a vyhodilo to exception, navic to, co skutecne odevzdali pred pulnoci neslo ani rozjet pres mvn kvuli preklepu v Pom...takze jsem nemel moc nervy to hodnotit....

mkrnul jsem ted na nejake to hodnoceni (odehnal)  "The interface seems that it does not make lot of sense from customer’s  point of view." (a zas to nemam nervy cele cist, jak to je dlouhy)
no to je, co jsem rikal... :+1:  ted tam tedy v tom nasem uz vsechno (na prvni pohled) funguje dik MichaloviK, mozna to chce jeste otestovat, ale ten layout je furt stejny ... nechapu proc je **My orders** pod tlacitkem na logout...
to je proste jedna z hlavnich funkci te aplikace, proc to neni na te hlavni liste Home, Tires atd...

ja se omlouvam, mel bych to treba sam implementovat, ale kodovani toho samotneho webu jsem fakt tupej...ale zas je treba se nejak domlouvit a ne si to navzajem prepisovat...

ja bych treba *nejak* zaridil skryti tech webfolderu jako je orders/detail/11 aby to nebylo v URL
coz by prispelo k security, ale popravde nevim jak *spravne/chytre* na to... nejaky redirect nebo session promenne fakt nevim....(?)

jinak tam jeste aktualne vidim, ze chybi nejaky centralni exception handling, neco jako toto https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc  nevim asi to nebylo v pozadavcich...? nicmene v tom TireController tam jsou interne nejake try catch, ja sem to tam tez mel, nez mi to prepsal ze, ale chtelo by to neaky ten exception controller... to bych mozna i zvlad, akorat dneska uz to nedava mozna zitra...

**Comment by m-krajcovic** [comment]
Nevim co ma tvoje hodnotenie inej skupiny spoločne s naším projektom ale ok
:D No to je fajn ze si napísal že ui je divne ale moc tomu nepomahas a
nikto na to nemal čas. Každopádne tie orders sú už jedno bo co je hlavne je
ze sa to da objednať z tabu Tires a nemusíš ist cez my orders... Keď sa to
kazdopadne niekomu chce prerábať a ma čas tak veselo do toho.
Ten detail v order je dobre a nedostane sa naň ani cez to url niekto kto
neni vlastníkom order alebo adminom
S tými exceptionami by sa zišlo niečo spraviť a hej vymazal som ti
nezmyselné Try catche a asi všetko lebo to vôbec nefungovalo. Sa na to
pozri a pouč sa ako na to v budúcnosti. Nechápem prečo sa sťažujes ze som
to opravil.

**Comment by mtravnicek** [comment]
aha no tak sorry ze jsem neco psal... mela to byt castecne reakce na Martina v kontextu tech hodnoceni, to ani nevim ze to ctes...
uvadim konkretni argumenty, co je spatne na tom UI... asi neni problem prohodit nejaka tlacitka...
mas pravdu, ze u toho Tires pribylo tlacitko Order, ale toto jsi tam dodelal az dodatecne, bavime se o tom, co tam pripadne zmenit.. a ty mi argumentujes ze nebyl cas... ja to klidne upravim sam...muzu?
asi udelam nejakou branch nebo tak...

jako asi bys taky nebyl moc nadseny, kdyby ti nekdo prepsal *cely* kod... protoze se mu nelibil...
jedine co tam bylo nefunkcni bylo vytvoreni te objednavky, jinak vypsani seznamu atd fungovalo akorat jsme se tam hadali o tom GET/POST, pripadne DELETE... ty try/catch tam zabranovaly vyjimce, jinak opravdu byli celkem nanic, ale mrkni na tirecontoller apod tam to maj i kdyz se redirectem...
to vytvoreni objednavky jsem uz nedaval i kdyz sem na tom sedel do pulnoci,
precejen ta objednavka je nejslozitejsi z tech entit, kdyz navic obsahovala to tire plus additional service,
a propojeni toho jsp formulare s controllerem bylo fakt o hubu, jak prenest ta data, dobry zes tam pak  na to samostatnou tridu, to smekam, pac tim se to celkem vyresilo, kdes to opsal :+1: 

k tomu aktualnimu kodu: tim, ze se na tu stranku **nedostane** myslis toto:

```
if (order != null && !userDetails.getAuthorities().contains(new SimpleGrantedAuthority("ADMIN")) &&
                !order.getUser().getEmail().equals(userDetails.getUsername())) {
            throw new AccessDeniedException("403");
        }
``` 
kdyz tam mas vedle @PreAuthorize("hasAuthority('ADMIN')")? navic tam tenhle kod je dvakrat...

nic zitra apod neco zkusim predelat a dat k posouzeni...

**Comment by m-krajcovic** [comment]
Sak len vravím že pred deadlinom na to čas nebol a preto to tam stále
zmenené neni. Teraz to stále vyzerá rovnako ale aspoň to dáva ako tak
zmysel. Pravdaže ako "eshop" to dosť suckuje.  keď sa ti to chce meniť tak
veselo do toho.
A nie nezmenil som ti všetko ale skoro v každej metóde boli dake drobnosti
napr na security co fakt nebudeme čakať hádam kym si každý dopíše jednu
anotaciu ku každej metóde. A nie nevadilo by mi keby mi niekto prepísal
nefunkčný kód namiesto mňa bo mi ušetrí čas a aspoň vidím ako to mozem
spraviť nabuduce. Tie catche co si tam mal len zakrývali chyby ktoré
vznikli ale nič s nimi nespravili co je ešte horšie ako ich nesledovať
vôbec.
Áno ten kód co si postol skontroluje ci je človek prezerajúci objednávku
admin alebo owner. Na tej metóde je len anotácia preauthorize isauthorized
a nie to co si poslal ty. Pravdaže sa to da vyriešiť aj lepšie ale henten
spôsob je dosť jednoduchý.

**Comment by mtravnicek** [comment]
ok prosimte, rad bych to spravil sam, ale jsem strasne pomaly plus ne uplne fit...
jak se vytvari ty objednavky, tire atd. tak tam nejsou uplne koser ty validace...
treba jde zadat jako adresa cislo v order, jako cislo pismena u tire, pak nulova cena, to je schvalne hm....
tam by to chtelo asi nejaky ten pattern @Pattern(regexp="[0-9]*") na to cislo atd, neumim regexy a nic..

jeste kdyz jsem to ted zkousel (sice pres jetty)
tak se mi stala takova vec, rekneme ze vytvarim tires
a visim nekde na
http://localhost:8080/pa165/tires/edit/12
pak **vyprsela session**, skocilo to na prihlaseni a dostal jsem
```
Problem accessing /tires/edit/12. Reason:
500  Server Error
org.apache.jasper.JasperException: An exception occurred processing JSP page /WEB-INF/jsp/tires/edit.jsp at line 14    (14:     <form:hidden path="id"  style="display:none"/>)

```
no nebyl jsem schopny to pak reprodukovat, a takto se to chova kdyz se tam zada nejake ID toho tire, ktere neexistuje.... ale tohle mi proste vyskocilo potom, co jsem tam nejak dal edit na ten tire...ciste pres to rozhrani....
ted jsem zkousel, kdyz visim na formulari Create New tire, vypsi session, (kterou muzu smazat v cookies),
dam crate tire, tak to pak hodi chybu POST not allowed apod, zadne presmerovani na prihlaseni proste chyba a hotovo....  tam tu session by chtelo jednak nejak prodlouzit viz
http://stackoverflow.com/questions/1406287/how-do-i-set-session-timeout-of-greater-than-30-minutes
nebo aby proste zustal uzivatel trvale prihlaseny *nejak*....plus by pri vyprseni session to melo nejak automaticky presmerovat asi na hlavni stranku apod. cim by se vyresili problemy s tim prerusenim

**Comment by mtravnicek** [comment]
jak vlastne funguje ten Login form... melo by se to poslat pres POST, ale na to zadny controller v HomeController ani jinde nevidim..?

**Comment by mtravnicek** [comment]
trosku jsem ted vylepsil a dodelavam tu validaci, jinak ohledne toho loginu/logoutu porad nevim..

**Comment by m-krajcovic** [comment]
Sak pri tej validacii cisel to funguje spravne, tie regexy tam urcite netreba .. hlavne regex je len na stringy, "size" v Tire je string lebo to nemusi byt nutne cislo. Takze neviem co na tom vlastne opravujes.

Ten login nechapem co s tym chces riesit, sak to ze vyprsi session nam moze byt ukradnute. No skusim sa pozret na to, ale nevidim moc dovod naco sa s tym trapit

**Comment by mtravnicek** [comment]
jasne za chvili to poslu...v tom loginu je problem jak visis treba na te strance create a das create pokud vyprsela session....tak ti to vyhodi POST not allowed..

**Comment by mtravnicek** [comment]
tak je to v nove branch mufix, kdytak na to mrkni a dej merge dik...

**Comment by mtravnicek** [comment]
@spisiakm @javorka @m-krajcovic 
ja nevim jeste zkusim do zitra mrknout na ten exception handling....update...
neni nahodou uz potom deadlinu...project done: 72 hours before your defence
takze uz jsme asi za ted za tim deadlinem, martin rikal ze se chce zitra potkat? ja jsem pro, kdyztak dejte vedet jak budete mit cas...

**Comment by spisiakm** [comment]
No dnes sa mi bude dat stretnut akurat tak mozno okolo siestej, skor nie
(nebudem v Brne). Dnes sa chcem este pozriet aj na tu prezentaciu (skusim
nieco vymysliet).

2017-01-08 17:48 GMT+01:00 mtravnicek <notifications@github.com>:

**Comment by mtravnicek** [comment]
jo vsak ohledne te prezentace , tak va 6 na skolnich PC? budu tam

**Comment by spisiakm** [comment]
Neviem ale či sa mi bude ešte dnes ako prídem chcieť ísť o šiestej do školy
:D skôr by som to už nechal na zajtra okolo obeda

**Comment by mtravnicek** [comment]
jasny, vecer dej vedet

**Comment by spisiakm** [comment]
Hej, dnes to uz fakt nestiham, a ani sa mi popravde velmi nechce, dajme to
na zajtra o 11:00

**Comment by mtravnicek** [comment]
ok tak v 11

**Comment by javorka** [comment]
Caute. Videl som pomerne bujnu diskusie a aj par commitov. Ja som nestihal koli skuskam :( Ako sme na tom? 
P.S. Cital som, ze sa chcete stretnut v skole. Co tam chcete preberat? Ak treba, tak pridem, ale inak mi to pride troska zbytocne, lebo uz aj tak nic neurobite (posledny commit sa rata 72h pred obhajobou).
@spisiakm @m-krajcovic @mtravnicek

**Comment by spisiakm** [comment]
Mne skôr ide o tu prezentáciu. Ako jasné, je to easy, len som chcel nejaké
nápady od každého :D

**Comment by spisiakm** [comment]
Alebo to môžme spraviť tak, že každý pošle jeden-dva slajdy, ktoré by chcel
odprezentovat, a potom to dáme dokopy

**Comment by spisiakm** [comment]
Chcete sa teda stretnúť, či to stačí takto ?

**Comment by m-krajcovic** [comment]
ja budem pri skole, ale je mi to uplne jedno :D mozme kludne z domu

**Comment by javorka** [comment]
Kludne sa mozme stretnut. Za nejaku polhodinku - hodinku si myslim, ze to spravime. 
Asi mi je to jedno ci sa stretneme, alebo to spravime z domu

**Comment by spisiakm** [comment]
Ok, idem do školy, za 20-25 min. By som tam mohol byť.

On Jan 10, 2017 10:24 AM, "javorka" <notifications@github.com> wrote:

Kludne sa mozme stretnut. Za nejaku polhodinku - hodinku si myslim, ze to
spravime.
Asi mi je to jedno ci sa stretneme, alebo to spravime z domu

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/javorka/PA165/issues/43#issuecomment-271526022>, or mute
the thread

**Comment by javorka** [comment]
Beriem to tak, ze by som tam mal prist teda? :smile: Za pol hodiny tam mozem byt

**Comment by mtravnicek** [comment]
pojdme-pojdte cca za tech 20 min..

**Comment by spisiakm** [comment]
Jj :D

**Comment by spisiakm** [comment]
Done, zatvaram
