### ISSUE TITLE
Create unit tests for entities

### ISSUE THREAD

**Issue by spisiakm** [javorka/PA165#5]
For each entity there will be a unit test. The person who created an entity cannot create a unit test for that entity, he must choose another entity.

**Comment by m-krajcovic** [comment]
Pridal som do svojho forku daky sample ako by mohol vyzerat setup testov : https://github.com/m-krajcovic/PA165/commit/0e47f458df953a367922e80ac7e13e76dbb8699d

Neviem ci je to uplne spravne, chcel som hlavne oddelit testovaci config od toho hlavneho, popripade napiste ako to ma byt lepsie

**Comment by javorka** [comment]
Spravil si to super! Dobra praca!

**Comment by javorka** [comment]
@m-krajcovic nespravis nejaky MR? alebo rovno push? chcel by som uz zacat pisat testy

**Comment by m-krajcovic** [comment]
Jo kludne, ja som s tym cakal, lebo by som nemal robit testy pre UserDao ked som ho vytvoril, ale hento asi vadit nebude

**Comment by m-krajcovic** [comment]
pushol som to

**Comment by spisiakm** [comment]
Musime sa dohodnut, ako s tymi testami. Len najskor asi bude treba, aby boli aspon tie 4 entity, ktore mame spravit, uz pushnute. A ten **UserDaoTest** asi aspon zlahka niekym inym upravit, aby sa nepovedalo 😄

**Comment by javorka** [comment]
Ja som zacal pisat UserDaoTest, pricom moju entitu mam v samostatnej branchi :) Potom pushnem aj ten test do osobitnej branche, ak by ste ho hladali

**Comment by m-krajcovic** [comment]
Tak zacnem robit testy na Tire, hadam na tom uz nikto nezacal robit :D

**Comment by spisiakm** [comment]
ja spravim test na AdditionalService, ak nikto nema namietky :)

**Comment by spisiakm** [comment]
vlastne to je blbost, spravim test na Order, aby @mtravnicek nerobil testy sam sebe :D

**Comment by spisiakm** [comment]
Ok, pushol som testy na `Order `+ som upravil metodu equals v class `Tire`, aby porovnavala `BigDecimal `hodnoty cez `compareTo `a nie cez `equals`, takze by uz nemalo vyhadzovat error, ked sa bude porovnavat `Tire `class cez `equals `iba preto, ze cena expected je **3000.00** a cena actual je **3000**.
Dufam, ze to uz je vsetko kodenie z mojej strany 😄

**Comment by spisiakm** [comment]
Chalani čo tie komenty :D
