### ISSUE TITLE
Class diagram

### ISSUE THREAD

**Issue by spisiakm** [javorka/PA165#6]
- Person
  - id
  - name
  - address
  - phone number
- Order
  - id
  - customerName
  - tire
  - vehicleType
  - date
  - service(s)

**Comment by m-krajcovic** [comment]
[pa165.vpp.zip](https://github.com/javorka/PA165/files/553797/pa165.vpp.zip)

**Comment by javorka** [comment]
Co hovorite na verziu:
1, pridat OrderItem
2, Tire prepojit s OrderItem
3, AdditionalService prepojit s OrderItem
4, Zrusit vsetky Service okrem AdditionalService?
chapete ma? nechce sa mi to tu kreslit

**Comment by m-krajcovic** [comment]
pozri #4 ,nevim teda co by oproti tomu ten orderitem vyriesil

**Comment by m-krajcovic** [comment]
tak podla diskusie z #4 som vytvoril toto
<img width="452" alt="screenshot 2016-10-27 10 29 06" src="https://cloud.githubusercontent.com/assets/6861709/19760089/3948af60-9c30-11e6-8ea7-1383d6a3bad8.png">

**Comment by spisiakm** [comment]
Nice, dnes skusim spravit este Use Case a hodim ho sem 👍
