### ISSUE TITLE
Nez se vrhnu na tu entitu Objednavka bych rad probral.... 

### ISSUE THREAD

**Issue by mtravnicek** [javorka/PA165#7]
ahoj, tak vidim ze to dost resite s tou pneumatikou v objednavce... podle me by pneu melo byt soucasti services ale pokud je receno v zadani ze to ma byt extra vec = tire tak tam dam tire.... prinejhorsim toto se da pak predelat, zas neni tak strasna vec abychom  tyden resili ano/ne kdyz to, co resime, je vlastne jak se vejit do napul blbeho-oklesteneho zadani... takze chceme splnit zadani nebo udelat dokonaly navrh... 
jen teda ciste z pohledu rozumu me prijde v poradku ze by si zakaznik pripadne objednal neco jineho nez pneumatiky, resp. neco bez pneumatik, jaky kdyz se stavim na benzinku tak taky nemusim povinne tankovat benzin atd.  Asi by bylo dobre se ohledne toho zeptat dopredu cviciciho,( zadavajiciho?), zda se to zadani muze trochu ohnout... ihmo ano a cele je to jen o tom si to pak obhajit, chce si nekdo napsat maila s dotazem? 

jeste bych prosel slovo od slova to zadani...

Vytvořte systém, ve kterém si bude moci zákazník vybrat nové obutí pro svoje vozidlo z nabídky pneuservisu. Pneuservis bude poskytovat **různé typy pneumatik**, velikosti, **od různých výrobců**, s různou cenou  (to je jasny). 

> Výběr zákazníka bude zaznamenán a evidován pod jeho jménem, adresou, telefonem a typem vozidla, které chce přezout

toto asi bude v te objednavce-- ?

. Kromě přezouvání bude pneuservis poskytovat i nějaké doprovodné služby, jakými může být kontrola sbíhavosti kol apod. Ty si může zákazník přiobjednat k přezutí kol. Jeden zákazník si může vytvořit více objednávek. Systém také bude schopný poskytnout přehled všech objednávek dle zákazníků, celkovou cenu obejdnávky apod.
zbytek mi prijde celkem jasny....
Co ted resim je, jak tu svou entitu kompletne neopsat z cviceni, kdyz tam v podstate je to same a proc to vymyslet znova....plus k tomu ty obludne hashcody a equals

**Comment by m-krajcovic** [comment]
Tak to je jasne, ze by clovek mohol chciet nieco ine ako prezutie pneumatik, ale tento system ma fungovat len na objednanie prezuvania pneumatik. Myslim, ze je zbytocne tam pridavat hocijaku funkcionalitu navyse, pretoze to nikto neohodnoti ziadnymi bonusovymi bodami. 
Cviciaci sa normalne vyjadril, ze tento projekt nesluzi na to vytvorit daky skvely system, ale skor vyskusat si tie technologie.

K tomu zadaniu a otazkam: myslim, ze je to docela fajn zahrnute v class diagrame https://github.com/javorka/PA165/wiki/Diagrams - co obsahuje objednavka atd. Ja uz teda pocitam ze toto moze byt finalny navrh, ked sa nikto nevyjadril uz proti.

**Comment by mtravnicek** [comment]
ok no neni cas to moc resit, ja to teda udelam Order podle toho diagramu...
ale hele ted jsem tam poslal tu svou branch, kde jsem delal nejake upravy v tom configu,
sice mi to nefunguje v main class v tom app, ale ten tvuj puvodni kod nejde vubec spustit, viz to setPackagesToScan atd...
tak na to kdyztak mrkni, jinak co se divam, co tam mas ted toho Usera plus to DAO, testy, nevim to mame prece delat na stridacku ne stejny entity a stejny test... atd nemate cas se jeste zitra potkat? a domluvit se.....

**Comment by m-krajcovic** [comment]
To co je momentalne v mastri ide uplne vpohode spustit (skusil som novy clone a mvn clean install aj mvn test).

Ohladom tych mojich testov - ano, nemal by som to robit ja. Pridal som to len ako ukazku nech mozte ked tak zacat robit na tom a ja pak spravim testy pre dake inde dao.

Kludne sa mozme stretnut zajtra.

**Comment by mtravnicek** [comment]
ok tak zitra se potkame v te centralni pocitacove studovne, v kolik? nekdy odpoledne az vecir asi

**Comment by mtravnicek** [comment]
viz toto http://stackoverflow.com/questions/29223359/spring-jpa-config-illegalargumentexception-no-persistence-unit-with-name-found

**Comment by javorka** [comment]
Caute, ja sa zajtra nebudem moct stretnut. Entitu som pushol do novej branche a testy napisem na usera kludne. Na nete budem do 18 ale potom uz nebudem moct. Nevadi borci?

**Comment by spisiakm** [comment]
ja dnes este dokoncim entitu tire + interface, potom to pushnem. Zajtra
este neviem, kedy pridem do brna, takze vam neviem povedat, kedy sa da
stretnut.

**Comment by m-krajcovic** [comment]
ja mozem tak do 17tej hocikedy

@mtravnicek skus si pullnut ten najnovsi commmit z mastru, malo by to ist vsetko

**Comment by mtravnicek** [comment]
ahoj michale, muzes se teda ted stavit do te centralni pocitacove v kolik? ja sem tam za minutku

**Comment by m-krajcovic** [comment]
tak idem tam, budem tam tak za 20 minut

**Comment by javorka** [comment]
ak bude treba tak sa stavim okolo 15:30 ak tam este budete. Moje veci su v osobitnych vetvach, ak chcete na nich stavat. Napiste prosim ci mam prist.

**Comment by mtravnicek** [comment]
ok nekde vzadu vpravo idealne.... jinak udelate nekdo prosim ten Use case? ja ty databaze/navrh znam jen tak zbezne..

**Comment by mtravnicek** [comment]
jo urcite prijd ja tam budu asi i s tim druhym michalem

**Comment by spisiakm** [comment]
Ja pridem do brna az za polhodinu, takze to asi uz nic. Nasli ste nieco, co treba doplnit/zmenit ? Inak potom spravim ten test na Order + opravim ten use case #8 , ak tam uz nic teda nechyba

**Comment by mtravnicek** [comment]
Martine, v tom use case schematu, jak tam je REGISTRATION -> CONFIRM REGISTRATION, tak nemelo by byt neco jako CREATE ORDER -> ACCEPT ORDER nebo PROCESS ORDER ATD...?
jinak furt sedim na PC v te pc hale....
jeste k tem equals.... mam v tom Order v equals i hashcode ORDER STATUS, neni to blbost, ja bych to vyhodil... kdyz se zmeni stav objednavky je to jina objednavka? (michale?)

**Comment by spisiakm** [comment]
no skor som to myslel tak, ze mu musi admin potvrdit registraciu, aby nebol v systeme hocikto, a iba registrovany zakaznik moze objednavat :)

btw pis to pls k tomu issue, #8 :)

**Comment by mtravnicek** [comment]
jo jinak nechci to na posledni chvili komplikvat ale porad si myslim, ze ty kontaktni udaje by mely
byt v tom USER, ne v tom ORDER...  objednavka je svazana s nejakym uzivatelem, to je jedno jestli je registrovany nebo ne... takhle kdyz vypisu objednavku... tak mi to vyhodi milion veci...
na co je ten objekt USER pak kdyz se vlastne nepouziva??

**Comment by spisiakm** [comment]
Teraz by som to uz mozno nechal tak, mozme to prerobit potom, ked sa skontroluje prvy milestone.

**Comment by mtravnicek** [comment]
ok no mam tu takovy problem v testu
kdyz u AdditionalService porovnavam BigDecimal
one.getPrice().equals(two.getPrice())
tak toto nefunguje - je tam nekde nejaka pitomy rozdil 1000.0  vs 1000.00 apod, viz ten commit co jsem ted delal ....

**Comment by m-krajcovic** [comment]
Pozri do mojich testov pre Tire. Tam to mam cez compareto

**Comment by mtravnicek** [comment]
ok dik uz to jede :+1: co ten ORDER STATUS teda mazu z hascode apod....a test odevzdano
