### ISSUE TITLE
Use case diagram

### ISSUE THREAD

**Issue by javorka** [javorka/PA165#8]
Create use case diagram(s)

**Comment by spisiakm** [comment]
Vytvoril som nejaky use case, mrknite na to, co by ste tam pridali/upravili.
[PneuservisUseCase.pdf](https://github.com/javorka/PA165/files/561609/PneuservisUseCase.pdf)

**Comment by m-krajcovic** [comment]
Super, len tie extends sipky su naopak :)

**Comment by spisiakm** [comment]
jj, to som tam nahadzal narychlo, robim na touchpade v buse 😆

**Comment by mtravnicek** [comment]
CREATE ORDER -> ACCEPT ORDER nebo PROCESS ORDER ATD...? takze nic?

**Comment by spisiakm** [comment]
ako kludne to tam mozem pridat, problem to nie je. Ostatni v pohode ?

**Comment by spisiakm** [comment]
Ok, updatnuty use case je tu
[PneuservisUseCase.pdf](https://github.com/javorka/PA165/files/562592/PneuservisUseCase.pdf)

Hodim ho aj na wiki :)

**Comment by spisiakm** [comment]
Tu je obrazok, aby ste nemuseli vkuse stahovat a rozklikavat
![pneuservisusecase](https://cloud.githubusercontent.com/assets/22591751/19867316/bc7d5de2-9fa3-11e6-8fc2-4488b0e87d79.png)
